name: pytest
on:
  push:
    branches:
      -"**"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: install dependencies
        run: pip install -r requirements.txt
      
      - name: run tests
        run: pytest
